In [1]:
import pandas as pd

In [4]:
house_data = pd.read_csv('Data/house_rental_data.csv.txt', index_col='Unnamed: 0')

In [6]:
house_data.head()

Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom  Price
1  1177.698      2           7        2            2         2  62000
2  2134.800      5           7        4            2         2  78000
3  1138.560      5           7        2            2         1  58000
4  1458.780      2           7        3            2         2  45000
5   967.776     11          14        3            2         2  45000

In [7]:
house_data.columns

Index(['Sqft', 'Floor', 'TotalFloor', 'Bedroom', 'Living.Room', 'Bathroom',
       'Price'],
      dtype='object')

In [8]:
feature_data = house_data[['Sqft', 'Floor', 'TotalFloor', 'Bedroom', 'Living.Room', 'Bathroom']]

In [9]:
target_data = house_data.Price

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
lr = LinearRegression()

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
trainX, testX, trainY, testY = train_test_split(feature_data,target_data)

In [14]:
lr.fit(trainX,trainY)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [15]:
trainX.shape

(483, 6)

In [16]:
testX.shape

(162, 6)

In [17]:
trainY.shape

(483,)

In [18]:
lr.coef_

array([   36.68682794,   953.13385643,   317.53918595, -2028.02171445,
       -2826.09690626,  3289.17912628])

In [19]:
lr.intercept_

775.5559945416026

In [20]:
testX[:1]

Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom
348  1231.068      2           7        3            2         2

In [21]:
lr.predict(testX[:1])

array([44910.67720987])

In [22]:
testY[:1]

348    38888
Name: Price, dtype: int64

In [23]:
v = lr.coef_ 

In [27]:
d = testX[:1]

In [25]:
v

array([   36.68682794,   953.13385643,   317.53918595, -2028.02171445,
       -2826.09690626,  3289.17912628])

In [28]:
d

Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom
348  1231.068      2           7        3            2         2

In [29]:
import numpy as np

In [35]:
np.sum(np.multiply(v,d),axis=1) + lr.intercept_

348    44910.67721
dtype: float64

In [36]:
np.multiply(v,d)

Sqft        Floor   TotalFloor      Bedroom  Living.Room  \
348  45163.979904  1906.267713  2222.774302 -6084.065143 -5652.193813   

        Bathroom  
348  6578.358253

In [37]:
lr.predict(testX)

array([ 44910.67720987,  50972.88609805, 120515.66624048,  78474.61278598,
        51241.69470076,  30104.16365535,  63023.95422443,  79233.2348719 ,
        62149.36832536,  40495.75118223,  46718.27654043, 118954.96537528,
       141541.60873563,  50025.25194783,  71614.18002527, 107879.13800964,
        35481.31500735,  51255.26468952,  32319.34150265,  45414.98303127,
        41233.48902797, 128929.01713472,  58881.62708758,  89501.27868474,
        56093.47575668,  75894.88757876,  76921.56115213,  58033.35516826,
       118824.43364145, 160107.94274106,  59083.64987646,  54630.75235653,
        40580.83035883,  58355.90259462,  43189.60910392,  94844.83755494,
        51251.74584683,  76612.84374813,  77686.65495927,  41517.36842895,
        33624.43724118,  43848.84304202,  37718.45107824,  78984.22716249,
        27685.08787079,  62632.35902295,  46052.30791614,  54147.8403739 ,
        65647.64259114,  53068.73026002,  57412.3630837 ,  47501.46694339,
        65051.97593888,  

In [38]:
lr.score(testX,testY)

0.7305103789431963

In [40]:
from sklearn.metrics import r2_score, mean_squared_error

In [41]:
pred = lr.predict(testX)

In [42]:
mean_squared_error(y_pred=pred, y_true=testY)

402348110.2408376

In [47]:
np.sum(np.square(testY -  pred))/162

402348110.2408376

In [48]:
from sklearn.preprocessing import PolynomialFeatures

In [53]:
for degree in range(1,4):
    pol = PolynomialFeatures(degree=degree)
    X_tf = pol.fit_transform(trainX)
    testX_tf = pol.transform(testX)
    lr = LinearRegression()
    lr.fit(X_tf,trainY)

    print ('Train Data : ',lr.score(X_tf,trainY))
    print ('Test Data : ',lr.score(testX_tf,testY))

Train Data :  0.6852718152182509
Test Data :  0.7305103789431966
Train Data :  0.7152538360176743
Test Data :  0.697159371376239
Train Data :  0.8083548711867452
Test Data :  0.2544737842473872


### Classification

In [54]:
emp_data = pd.read_csv('Data/HR_comma_sep.csv.txt')

In [56]:
emp_data.rename(columns={'sales':'department'},inplace=True)

In [59]:
emp_data.left.value_counts()

0    11428
1     3571
Name: left, dtype: int64

In [60]:
emp_data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [61]:
emp_data.department.value_counts()

sales          4140
technical      2720
support        2229
IT             1227
product_mng     902
marketing       858
RandD           787
accounting      767
hr              739
management      630
Name: department, dtype: int64

In [62]:
emp_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
satisfaction_level       14999 non-null float64
last_evaluation          14999 non-null float64
number_project           14999 non-null int64
average_montly_hours     14999 non-null int64
time_spend_company       14999 non-null int64
Work_accident            14999 non-null int64
left                     14999 non-null int64
promotion_last_5years    14999 non-null int64
department               14999 non-null object
salary                   14999 non-null object
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB


In [63]:
num_data = emp_data.select_dtypes(include=['int64','float64'])

In [88]:
num_data = num_data[['satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident',
       'promotion_last_5years']]

In [68]:
salary_col = emp_data.salary.map({'low':1,'medium':2,'high':3})

In [69]:
from sklearn.preprocessing import LabelBinarizer

In [70]:
lb = LabelBinarizer()

In [73]:
depart_col = lb.fit_transform(emp_data.department)

In [89]:
feature_data = np.hstack([num_data,salary_col.values.reshape(-1,1),depart_col])

In [90]:
trainX,testX, trainY,testY = train_test_split(feature_data, emp_data.left)

In [95]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [92]:
lr = LogisticRegression()

In [93]:
lr.fit(trainX,trainY)

/home/awantik/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [94]:
lr.score(testX,testY)

0.7901333333333334

In [96]:
rf = RandomForestClassifier()

In [98]:
rf.fit(trainX,trainY)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [99]:
rf.score(testX,testY)

0.9904

In [102]:
from sklearn.preprocessing import StandardScaler

In [103]:
ss = StandardScaler()

In [105]:
X  = ss.fit_transform(house_data)

In [112]:
np.std(X[:,2])

1.0

In [113]:
house_data.describe()

Sqft       Floor  TotalFloor     Bedroom  Living.Room  \
count   645.000000  645.000000  645.000000  645.000000   645.000000   
mean   1527.656260    5.939535   10.855814    2.837209     1.813953   
std     767.386531    3.884721    4.996208    1.010740     0.462364   
min     359.358000    1.000000    1.000000    1.000000     0.000000   
25%     925.080000    3.000000    7.000000    2.000000     2.000000   
50%    1423.200000    5.000000   12.000000    3.000000     2.000000   
75%    1892.856000    8.000000   14.000000    4.000000     2.000000   
max    5856.468000   22.000000   38.000000    7.000000     4.000000   

         Bathroom          Price  
count  645.000000     645.000000  
mean     1.810853   61986.823256  
std      0.683574   35635.091007  
min      0.000000    6100.000000  
25%      1.000000   39000.000000  
50%      2.000000   50000.000000  
75%      2.000000   75000.000000  
max      5.000000  250000.000000